# Generated by Django 5.0 on 2023-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID товара"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("price", models.FloatField(verbose_name="Цена")),
            ],
        ),
    ]
